version: "3.8"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=clarity_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - clarity-network

  backend:
    build:
      context: ./backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    environment:
      - DEBUG=0
      - SECRET_KEY=changeme_in_prod
      - DATABASE=postgres
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=clarity_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - CORS_ALLOWED_ORIGINS=http://localhost
    depends_on:
      - db
    networks:
      - clarity-network

  frontend:
    build:
      context: ./frontend
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - clarity-network

networks:
  clarity-network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
